// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yuoulkkqfxknjrvrxjtg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1b3Vsa2txZnhrbmpydnJ4anRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NDYyNTYsImV4cCI6MjA2MzQyMjI1Nn0.fnNn-DBsjN-obhN-SZseljjggnRDl1vNVW8zbJC38Pk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);